### ISSUE TITLE
Why huge maps twice: KEYToString and  KEYNames?

### ISSUE THREAD

**Issue by guettli** [holoplot/go-evdev#14]
I noticed that that there are two huge maps, which are almost identical:

```

var KEYToString = map[EvCode]string{
	KEY_RESERVED:   "KEY_RESERVED",
	KEY_ESC:        "KEY_ESC",
	KEY_1:          "KEY_1",
	KEY_2:          "KEY_2",
	KEY_3:          "KEY_3",
...
```

And

```
var KEYNames = map[EvCode]string{
	KEY_RESERVED:   "KEY_RESERVED",
	KEY_ESC:        "KEY_ESC",
	KEY_1:          "KEY_1",
	KEY_2:          "KEY_2",
	KEY_3:          "KEY_3",
...
```

Is there a reason for this, or is this just a typo?

**Comment by gethiox** [comment]
@guettli
Because different names can point to the very same keycode (for example `KEY_DIRECTION` and `KEY_ROTATE_DISPLAY` points to the same code number), table has been split for string conversion and debug information separately.

First map `KEYToString` provides only one name for given keycode (first found in header files), this is used for conversion from keycode to string representation that can be easily reversed later with `KEYFromString` (`XFromString` actually provides conversion for all keycode aliases by the way).

`KEYNames` However, provides all aliases separated with slash, its purpose is debug/information only.
as an example:
```go
KEY_ALL_APPLICATIONS: "KEY_ALL_APPLICATIONS/KEY_DASHBOARD",
KEY_COFFEE: "KEY_COFFEE/KEY_SCREENLOCK",
KEY_ROTATE_DISPLAY: "KEY_ROTATE_DISPLAY/KEY_DIRECTION",
KEY_BRIGHTNESS_AUTO: "KEY_BRIGHTNESS_AUTO/KEY_BRIGHTNESS_ZERO",
BTN_GAMEPAD: "BTN_GAMEPAD/BTN_SOUTH/BTN_A",
BTN_NORTH: "BTN_NORTH/BTN_X",
BTN_WEST: "BTN_WEST/BTN_Y",
```

You can argue if two tables has some real value in the library, for many usecases `KeyToString` representation is good enough. It was my idea to make it that way, memory cost of such additional table is negligible but on the other hand it adds a little bit of complexity at generating process.

**Comment by zonque** [comment]
@gethiox Thanks for answering this one.
@guettli Let me know if that answer satisfies you and the issue can be closed.

**Comment by guettli** [comment]
@gethiox thank you for the explanation. I had a rough look at both maps, and overlooked entries like `"KEY_COFFEE/KEY_SCREENLOCK"`.

Why not add a comment like this, to make it more clear:

```Go
// KEYNames maps from EvCode to a string.
// If one EvCode has two string representations, both are seperated by a slash.
// Example: KEY_COFFEE: "KEY_COFFEE/KEY_SCREENLOCK"
var KEYNames = map[EvCode]string{
...
```
I think this would help new users to understand that.

I could create a PR, but feel free to just do it yourself - whatever is more convenient for you.

**Comment by gethiox** [comment]
I think commenting that is a great idea, I made required changes in #15
We can't easily comment specific `XNames` block, but there is a comment at the begging of `XNames` sections, should be sufficient.
